[tools]
"aqua:neovim/neovim" = "latest"
bitwarden = "latest"
bun = "latest"
caddy = "latest"
chezmoi = "latest"
claude = "latest"
cloudflared = "latest"
crystal = "latest"
deno = "latest"
elixir = "latest"
eza = "latest"
gleam = "latest"
go = "latest"
gradle = "latest"
haskell = "latest"
janet = "latest"
jj = "latest"
nim = "latest"
node = "latest"
ollama = "latest"
opencode = "latest"
opentofu = "latest"
pipx = "latest"
rg = "latest"
ruby = "latest"
sqlc = "latest"
supabase = "latest"
turso = "latest"
wren = "latest"
yazi = "latest"
zig = "latest"
zola = "latest"

[settings]

[settings.ruby]
compile = false
