"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$python\
$nodejs\
$rust\
$golang\
$c\
$cpp\
$java\
$status\
$character"""

right_format = """
$cmd_duration\
$time\
$memory_usage\
$battery\
"""

[username]
show_always = true
format = "[$user]($style) "
style = "bold purple"

[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "bright-black"

[directory]
format = "[󰉋 $path]($style) "
style = "blue"
truncation_length = 3
truncate_to_repo = true

[status]
disabled = false
format = "[󰅖 $status]($style) "
style = "red"

[git_branch]
format = "[󰘬 $branch]($style) "
style = "bright-black"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "cyan"

conflicted = " 󰞇 CONFLICT:$count"
untracked = " 󰋔 NEW:$count"
modified = " 󰏫 MOD:$count"
staged = " 󰐕STAGED:$count"
renamed = " 󰑕 RENAMED:$count"
deleted = " 󰆴 DELETED:$count"
stashed = " 󰏗 STASH:$count"

ahead = " 󰁝 AHEAD:$count"
behind = " 󰁅 BEHIND:$count"
diverged = " 󰁝 AHEAD:${ahead_count} 󰁅 BEHIND:${behind_count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style) '
style = "bright-black"

[cmd_duration]
min_time = 2000
format = "[󰔚 $duration]($style) "
style = "bold dimmed white"

[python]
format = "[$symbol ]($style)([$virtualenv ](bold white))"
style = "bold yellow"
symbol = ""
detect_files = []

[nodejs]
format = "[$symbol]($style)"
symbol = " "
style = "bold green"
detect_files = ["package.json"]

[rust]
format = "[$symbol]($style)"
symbol = " "
style = "bold red"
detect_files = ["Cargo.toml"]

[golang]
format = "[$symbol]($style)"
symbol = " "
style = "bold cyan"
detect_files = ["go.mod"]

[c]
format = "[$symbol]($style)"
symbol = " "
style = "bold blue"
detect_files = ["*.c", "*.h", "Makefile", "CMakeLists.txt"]
detect_extensions = ["c", "h"]

[cpp]
format = "[$symbol]($style)"
symbol = " "
style = "bold blue"
detect_files = ["*.cpp", "*.hpp", "*.cc", "CMakeLists.txt"]
detect_extensions = ["cpp", "hpp", "cc", "cxx"]

[java]
format = "[$symbol]($style)"
symbol = " "
style = "bold red"
detect_files = ["pom.xml", "build.gradle", "gradlew"]
detect_extensions = ["java"]

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[time]
disabled = false
format = "[ $time]($style)"
style = "bright-black"
time_format = "%H:%M"

[memory_usage]
disabled = false
threshold = 70
format = " [󰍛 $ram_pct]($style)"
style = "yellow"

[battery]
disabled = false
format = " [󰁹 $percentage]($style)"
style = "green"
